name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Extrair versão do arquivo pom.xml
        id: extract-version
        run: echo "::set-output name=version::$(grep -m1 '<version>' pom.xml | sed 's/[^0-9.]//g')"

      - name: Criar release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.extract-version.outputs.version }}
          tag_name: v${{ steps.extract-version.outputs.version }}
